name: Bump

on:
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump Versions
        uses: remorses/bump-version@v8
        with:
            version_file: ./module-contrib/version
            prefix: "plugsched version: "
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
