name: TagWhenVersionBump

on:
  push:
    paths:
      - 'module-contrib/version'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read version
        run: |
          export VERSION=$(cat ./module-contrib/version | awk '{print $NF}')
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION }}
          message: ""
